### ISSUE TITLE
Unable to find referenced value, 'AWS::Region'

### ISSUE THREAD

**Issue by scottwestover** [champgm/cloudformation-yaml-validator#5]
The plugin shows an error when `AWS::Region` is referenced. 

`AWS::Region` is a pseudo parameter - [reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html)

![Screen Shot 2019-03-20 at 9 20 00 AM](https://user-images.githubusercontent.com/9931822/54687181-5aa75400-4af1-11e9-8db4-c78927bf3016.png)

Example Snippet:
```
ECSRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${DeploymentStage}-ECSRole-${AWS::Region}
```
