### ISSUE TITLE
Unable to find referenced sub stack output

### ISSUE THREAD

**Issue by scottwestover** [champgm/cloudformation-yaml-validator#6]
Error: `Unable to find referenced sub stack output, 'ExternalLoadBalancer.DNSName'`

![Screen Shot 2019-03-20 at 9 26 48 AM](https://user-images.githubusercontent.com/9931822/54687570-4e6fc680-4af2-11e9-85b7-a3a7a8712354.png)

Example Snippet:
```
ExternalLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${DeploymentStage}-external-elb

AliasTarget:
        DNSName: !GetAtt ExternalLoadBalancer.DNSName
        HostedZoneId: !GetAtt ExternalLoadBalancer.CanonicalHostedZoneID
```

The plugin is throwing an error when trying to get an attribute from another stack in the resource section of the template.

**Comment by scottwestover** [comment]
Another example:
```Unable to find referenced sub stack output, 'NatGatewayEIP.AllocationId'```

Example Snippet:
```
NatGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-nat-gateway
```

![Screen Shot 2019-03-20 at 9 32 00 AM](https://user-images.githubusercontent.com/9931822/54687886-07ce9c00-4af3-11e9-8f29-75cc8cd7b3b2.png)
